
feature: ['feature/*', 'feat/*', 'test/*']
fix: ['fix/*', 'hotfix/*', 'bugfix/*']
chore: ['chore/*']
refactor: ['refactor/*']
style: ['style/*']
revert: ['revert/*']
remove: ['remove/*']
skip-changelog: [
  'dev/*',
  'testing',
  'test/*',
  'doc/*',
  'post/*'
]
