[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=7776000"
    Referrer-Policy = "no-referrer-when-downgrade"
    
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = '''
    public,
    max-age=604800
    '''
