/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefaultRouteImport } from './routes/_default'
import { Route as DefaultIndexRouteImport } from './routes/_default/index'
import { Route as DefaultPlaygroundRouteImport } from './routes/_default/playground'
import { Route as DefaultNotesRouteImport } from './routes/_default/notes'
import { Route as DefaultBlogRouteImport } from './routes/_default/blog'
import { Route as CategorySlugRouteImport } from './routes/$category.$slug'

const DefaultRoute = DefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultIndexRoute = DefaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultPlaygroundRoute = DefaultPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultNotesRoute = DefaultNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DefaultRoute,
} as any)
const DefaultBlogRoute = DefaultBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => DefaultRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/$category/$slug',
  path: '/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultIndexRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/blog': typeof DefaultBlogRoute
  '/notes': typeof DefaultNotesRoute
  '/playground': typeof DefaultPlaygroundRoute
}
export interface FileRoutesByTo {
  '/$category/$slug': typeof CategorySlugRoute
  '/blog': typeof DefaultBlogRoute
  '/notes': typeof DefaultNotesRoute
  '/playground': typeof DefaultPlaygroundRoute
  '/': typeof DefaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_default': typeof DefaultRouteWithChildren
  '/$category/$slug': typeof CategorySlugRoute
  '/_default/blog': typeof DefaultBlogRoute
  '/_default/notes': typeof DefaultNotesRoute
  '/_default/playground': typeof DefaultPlaygroundRoute
  '/_default/': typeof DefaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$category/$slug' | '/blog' | '/notes' | '/playground'
  fileRoutesByTo: FileRoutesByTo
  to: '/$category/$slug' | '/blog' | '/notes' | '/playground' | '/'
  id:
    | '__root__'
    | '/_default'
    | '/$category/$slug'
    | '/_default/blog'
    | '/_default/notes'
    | '/_default/playground'
    | '/_default/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DefaultRoute: typeof DefaultRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/': {
      id: '/_default/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/playground': {
      id: '/_default/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof DefaultPlaygroundRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/notes': {
      id: '/_default/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof DefaultNotesRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_default/blog': {
      id: '/_default/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof DefaultBlogRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/$category/$slug': {
      id: '/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/$category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DefaultRouteChildren {
  DefaultBlogRoute: typeof DefaultBlogRoute
  DefaultNotesRoute: typeof DefaultNotesRoute
  DefaultPlaygroundRoute: typeof DefaultPlaygroundRoute
  DefaultIndexRoute: typeof DefaultIndexRoute
}

const DefaultRouteChildren: DefaultRouteChildren = {
  DefaultBlogRoute: DefaultBlogRoute,
  DefaultNotesRoute: DefaultNotesRoute,
  DefaultPlaygroundRoute: DefaultPlaygroundRoute,
  DefaultIndexRoute: DefaultIndexRoute,
}

const DefaultRouteWithChildren =
  DefaultRoute._addFileChildren(DefaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DefaultRoute: DefaultRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
