name: unit test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn

      - uses: mattallty/jest-github-action@v1
        with:
          test-command: yarn test
          coverage-comment: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
